# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Here it's Prometheus itself.
scrape_configs:
  - job_name: "prometheus"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    scrape_interval: 5s
    static_configs:
      - targets: ["127.0.0.1:9090"]

  - job_name: "my-spring-actuator"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 2s
    static_configs:
      - targets: ["192.168.1.6:8081"] #youIP:app-port-> cmd -> ipconfig -> ipv4
        labels:
          application: "Video streaming Application"
